# Generated by Django 4.0.1 on 2022-01-11 10:48

from django.db import migrations, models
import overflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0002_alter_answer_id_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=overflow.models.upload_path),
        ),
    ]
